### ISSUE TITLE
failed to run this action when trigger workflow on PR to the upstream

### ISSUE THREAD

**Issue by yin1999** [softprops/diffset#13]
I'm going to get the diffset between upstream main branch and a branch from another repo. But this action seems only using branch branch name for compare. So the request will get a 404.

This is a example: https://github.com/mdn/translated-content/actions/runs/3553028215/jobs/5968307276#step:2:12

I'm not sure is there any plan on this

**Comment by chenrui333** [comment]
close it is stale, please open a new one if it is still the case.
